#!/bin/sh

[ -z $XDG_CONFIG_HOME ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z $XDG_DATA_HOME ] && export XDG_DATA_HOME="$HOME/.local/share"
[ -z $XDG_CACHE_HOME ] && export XDG_CACHE_HOME="$HOME/.cache"

[ -f $XDG_CONFIG_HOME/env/env.sh ] && source $XDG_CONFIG_HOME/env/env.sh

# Make terminal advertise 256 color support (from Ubuntu default .bash_profile)
if [ "$TERM" = "xterm" ] ; then
  if [ -z "$COLORTERM" ] ; then
    if [ -z "$XTERM_VERSION" ] ; then
      echo "Warning: Terminal wrongly calling iteself 'xterm'."
    else
      case "$XTERM_VERSION" in
        "XTerm(256)") TERM="xterm-256color" ;;
        "XTerm(88)") TERM="xterm-88color" ;;
        "XTerm") ;;
        *)
          echo "Warning: Unrecognized XTERM_VERSION: $XTERM_VERSION"
          ;;
      esac
    fi
  else
    case "$COLORTERM" in
      gnome-terminal)
        # Those crafty Gnome folks require you to check COLORTERM,
        # but don't allow you to just *favor* the setting over TERM.
        # Instead you need to compare it and perform some guesses
        # based upon the value. This is, perhaps, too simplistic.
        TERM="gnome-256color"
        ;;
      *)
        echo "Warning: Unrecognized COLORTERM: $COLORTERM"
        ;;
    esac
  fi
fi
