#!/bin/sh

[[ -z $XDG_CONFIG_HOME ]] && export XDG_CONFIG_HOME="$HOME/.config"
[[ -z $XDG_DATA_HOME ]] && export XDG_DATA_HOME="$HOME/.local/share"
[[ -z $XDG_CACHE_HOME ]] && export XDG_CACHE_HOME="$HOME/.cache"
[[ -f $XDG_CONFIG_HOME/bash/xdg.sh ]] && source $XDG_CONFIG_HOME/bash/xdg.sh

[[ -f $XDG_CONFIG_HOME/bash/env.sh ]] && source $XDG_CONFIG_HOME/bash/env.sh

# Set background image
feh --bg-scale ~/.config/wallpaper/disintegrate.jpg

source $XDG_CONFIG_HOME/bash/bashrc

xrdb $XDG_CONFIG_HOME/x/resources

# Disable screen blanking
xset -dpms; xset s off

# Use a normal cursor for X
xsetroot -cursor_name left_ptr

# Enable custom keyboard mappings
xmodmap $XDG_CONFIG_HOME/x/modmap

# Disable touchpad while typing
syndaemon -t -k -i 2 -d &

# Enable key remapping
xbindkeys -f $XDG_CONFIG_HOME/x/bindkeys

# Fix for Chromium Issue #370022
xcompmgr -a &

# Open web browser
xdg-open http:// &
