#!/bin/sh

# Set background image
feh --bg-scale ~/.config/wallpaper/disintegrate.jpg

source $XDG_CONFIG_HOME/bash/bashrc

xrdb $XDG_CONFIG_HOME/x/resources

# Disable screen blanking
xset -dpms; xset s off

# Use a normal cursor for X
xsetroot -cursor_name left_ptr

# Enable custom keyboard mappings
xmodmap $XDG_CONFIG_HOME/x/modmap

# Disable touchpad while typing
syndaemon -t -k -i 2 -d &

# Enable key remapping
xbindkeys -f $XDG_CONFIG_HOME/x/bindkeys

# Fix for Chromium Issue #370022
xcompmgr -a &

# Open web browser
xdg-open http:// &
