#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import dbus
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib

if __name__ == '__main__':
    DBusGMainLoop(set_as_default=True)

    bus = dbus.SessionBus()
    bus.add_signal_receiver(
        lambda x: print(x),
        dbus_interface='org.xmonad.Log')

    loop = GLib.MainLoop()
    loop.run()
