#!/usr/bin/env zsh

source $XDG_CONFIG_HOME/env/env.sh
source $XDG_CONFIG_HOME/env/posix/functions.sh
source $XDG_CONFIG_HOME/env/aliases.sh

# vi keybindings
bindkey -v

# make backspace work in insert mode
bindkey '^?' backward-delete-char

export HISTFILE=$XDG_DATA_HOME/zsh/history
mkdir -p $(dirname $HISTFILE) && touch $HISTFILE

export SAVEHIST=50000

# Share history between all shells
setopt inc_append_history
setopt share_history
setopt hist_reduce_blanks

# Trim blanks in history
setopt hist_reduce_blanks

autoload -Uz vcs_info

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

emulate bash -c "[[ -f $HOME/.bash_profile ]] && source $HOME/.bash_profile"
emulate bash -c "[[ -f $HOME/.local/bashrc ]] && source $HOME/.local/bashrc"

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan'

ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[function]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=red'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=red'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=red'

source $XDG_CONFIG_HOME/env/prompt.sh
source $XDG_CONFIG_HOME/zsh/prompt.zsh

function source_plugin() {
    local plugin=$1
    local plugin_path=(/usr/share/zsh/plugins /usr/local/share $HOME/.linuxbrew/share)

    for dir in $plugin_path; do
        local script="$dir/$plugin"

        if [ -f "$script" ]; then
            source "$script"
            return
        fi
    done
}

source_plugin zsh-autosuggestions/zsh-autosuggestions.zsh
source_plugin zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

unfunction source_plugin
