#!/usr/bin/env zsh

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

source $XDG_CONFIG_HOME/env/env.sh
source $XDG_CONFIG_HOME/env/posix/functions.sh
source $XDG_CONFIG_HOME/env/aliases.sh

# zsh package manager
source $XDG_CONFIG_HOME/zsh/antigen/antigen.zsh

# vi keybindings
bindkey -v

# make backspace work in insert mode
bindkey '^?' backward-delete-char

export HISTFILE=$XDG_DATA_HOME/zsh/history
mkdir -p $(dirname $HISTFILE) && touch $HISTFILE

export SAVEHIST=50000

# Share history between all shells
setopt inc_append_history
setopt share_history

# Trim blanks in history
setopt hist_reduce_blanks

autoload -Uz vcs_info

# fish-style autosuggestions
antigen bundle zsh-users/zsh-autosuggestions

# syntax highlighting must be bundled last
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[command]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[alias]='fg=cyan'

ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[function]='fg=yellow'

source $XDG_CONFIG_HOME/env/prompt.sh
source $XDG_CONFIG_HOME/zsh/prompt.zsh
