#!/bin/bash

source $XDG_CONFIG_HOME/env/posix/functions.sh
source $XDG_CONFIG_HOME/env/aliases.sh

# History settings
# Create the history file if it doesn't exist
export HISTFILE="$XDG_DATA_HOME/bash/history"
[[ ! -f $(dirname $HISTFILE) ]] && mkdir -p $(dirname $HISTFILE)
export HISTCONTROL=ignoredups:erasedups
shopt -s histappend
# Sync history across multiple terminals (useful for tmux)
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Disable flow control. Instead pass Ctrl-S and Ctrl-Q through.
stty -ixon

# If a local bashrc exists, then source it (overriding other configuration)
[[ -f $HOME/.local/bashrc ]] && source $HOME/.local/bashrc
