#!/bin/sh

set -eux

# Use the "logo" key as the primary modifier
mod="Mod4"

# Open the terminal
riverctl map normal $mod+Shift Return spawn alacritty

# Spawn a program launcher
riverctl map normal $mod P spawn bemenu-run

# Mod+Shift+C to close the focused view
riverctl map normal $mod+Shift C close

# Mod+Shift+Q to exit river
riverctl map normal $mod+Shift Q exit

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile by 5%
riverctl map normal $mod H send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal $mod L send-layout-cmd rivertile 'main-ratio +0.05'

# Screenshots
# shellcheck disable=SC2016
screenshot_path='$(xdg-user-dir PICTURES)/screenshot/$(date --iso-8601).png'
riverctl map normal $mod S spawn "grim ${screenshot_path}"
riverctl map normal $mod+Shift S spawn "slurp | grim -g - ${screenshot_path}"

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << (i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod "$i" set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift "$i" set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control "$i" toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control "$i" toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+T to toggle float
riverctl map normal $mod T toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Audio volume
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer -q set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer -q set Master 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer -q set Master toggle'

    # Backlight
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl float-filter-add app-id "float"
riverctl float-filter-add app-id "popup"

# Behavior
riverctl focus-follows-cursor normal

# Appearance
riverctl border-width 1
riverctl border-color-unfocused '0x393939'
riverctl border-color-focused '0xfff700'

# GTK 3 settings.ini is ignored on Wayland, so we need to set the settings
# manually on startup via gsettings.
#
# https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland
gtk_settings="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$gtk_settings" | cut -d'=' -f2)"
icon_theme="$(grep 'gtk-icon-theme-name' "$gtk_settings" | cut -d'=' -f2)"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$gtk_settings" | cut -d'=' -f2)"
font_name="$(grep 'gtk-font-name' "$gtk_settings" | cut -d'=' -f2)"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"

# Fix for GTK 3 applications hanging on start.
# https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK

# Start Waybar
riverctl spawn waybar

# Wallpaper
swaybg --image "$XDG_CONFIG_HOME/wallpaper/disintegrate.jpg" &

# Set the layout on startup
riverctl default-layout rivertile
exec rivertile \
  -outer-padding 0 \
  -view-padding 0 \
  -main-ratio 0.5
