#!/bin/sh

# based on https://stackoverflow.com/a/30998048/959847

set -euo pipefail

usage() {
  cat <<EOF
  Shows the merge commit that contains a given commit.

  usage: git show-merge <revision>
     or: git show-merge <revision> <branch>
EOF
}

find_merge() {
  commit=$1
  branch=$2

  (
    git rev-list "$commit..$branch" --ancestry-path | cat -n
    git rev-list "$commit..$branch" --first-parent | cat -n
  ) | sort -k2 -s | uniq -f1 -d | sort -n | tail -1 | cut -f2
}


if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  usage
  exit
fi

commit=$1
branch=${2:-HEAD}

merge=$(find_merge "$commit" "$branch")
if [ -n "$merge" ]; then
  git show "$merge"
fi
